### ISSUE TITLE
`yarn start` error

### ISSUE THREAD

**Issue by yubrshen** [saharmor/whisper-playground#14]
When executing `cd interface && yarn start`
in a newly opened terminal, I got the error:
```
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/yshen/dev/whisper-playground/interface/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/yshen/dev/whisper-playground/interface/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/yshen/dev/whisper-playground/interface/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/yshen/dev/whisper-playground/interface/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/yshen/dev/whisper-playground/interface/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/yshen/dev/whisper-playground/interface/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/yshen/dev/whisper-playground/interface/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/yshen/dev/whisper-playground/interface/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/home/yshen/dev/whisper-playground/interface/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/yshen/dev/whisper-playground/interface/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/yshen/dev/whisper-playground/interface/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/yshen/dev/whisper-playground/interface/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/yshen/dev/whisper-playground/interface/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/yshen/dev/whisper-playground/interface/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/yshen/dev/whisper-playground/interface/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/yshen/dev/whisper-playground/interface/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/yshen/dev/whisper-playground/interface/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I also noticed when executing `yarn start` the second time, a web page is opened, at URL:http://localhost:3000
with an error message:
```
Hmmm… can't reach this pagelocalhost refused to connect.
Try:

Search the web for [localhost](https://www.bing.com/search?form=ANLKDR&q=localhost)
Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_REFUSED
```

**Comment by saharmor** [comment]
This seems like a local error on your end. Maybe try this https://roytuts.com/how-to-fix-err_ossl_evp_unsupported-in-react-js-application/?

**Comment by MarcoBI24** [comment]
Hello, the same thing just happened, the solution is to change thein the package.json: "**react-scripts --openssl-legacy-provider start**". I hope I can help you people.



![Captura desde 2023-01-24 16-50-49](https://user-images.githubusercontent.com/98546233/214428953-52cd90ed-790f-4960-8915-6612dad67452.png)

**Comment by saharmor** [comment]
Thanks @MarcoBI24. I'll add it to package.json if this appears to be a common error.

**Comment by saharmor** [comment]
Closing for now, feel free to reopen if still relevant.

**Comment by yubrshen** [comment]
@MarcoBI24 Yes, with the change suggested by you. The error is gone. I can start the frontend (interface).
Thanks!

**Comment by MarcoBI24** [comment]
@saharmor,
@yubrshen
To serve you bro.
