### ISSUE TITLE
Error occurred during backend connection.

### ISSUE THREAD

**Issue by Epresin** [saharmor/whisper-playground#34]
```
(whisper-playground) E:\whisper\whisper-playground>cd backend

(whisper-playground) E:\whisper\whisper-playground\backend>python server.py
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
======== Running on http://0.0.0.0:8000 ========
(Press CTRL+C to quit)
INFO:root:Client connected, initializing stream...
INFO:root:Stream configuration received: {'beamSize': '1', 'transcribeTimeout': '5', 'transcriptionMethod': 'real-time', 'model': 'small', 'language': 'english'}
WARNING:faster_whisper:An error occured while synchronizing the model guillaumekln/faster-whisper-small.en from the Hugging Face Hub:
Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.
WARNING:faster_whisper:Trying to load the model directly from the local cache, if it exists.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\whisper-playground\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\whisper-playground\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\whisper-playground\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\ProgramData\Anaconda3\envs\whisper-playground\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "E:\whisper\whisper-playground\backend\client_manager.py", line 15, in create_new_client
    new_client = initialize_client(sid, sio, config)
  File "E:\whisper\whisper-playground\backend\clients\utils.py", line 56, in initialize_client
    transcriber = WhisperTranscriber(model_name=whisper_model.value, language_code=language_code, beam_size=beam_size)
  File "E:\whisper\whisper-playground\backend\transcription\whisper_transcriber.py", line 29, in __init__
    self.model = WhisperModel(self.get_full_model_name(model_name, language_code), device=device,
  File "C:\ProgramData\Anaconda3\envs\whisper-playground\lib\site-packages\faster_whisper\transcribe.py", line 124, in __init__
    self.model = ctranslate2.models.Whisper(
RuntimeError: Unable to open file 'model.bin' in model 'C:\Users\admin\.cache\huggingface\hub\models--guillaumekln--faster-whisper-small.en\snapshots\4e49ce629e3fa4c3da596c602b212cb026910443'
```

"The web page is using the default settings with the 'small' model in English for real-time usage. However, when connecting to the backend, an error occurs. The backend seems to be using a previous version of the automatically downloaded model."

**Comment by ethanzrd** [comment]
Are you sure that you were connected to the internet? If there's an existing full installation (one that hadn't cut off) on your disk, this shouldn't be happening. Could you try with another model you haven't downloaded yet?

**Comment by Epresin** [comment]
```
(whisper) D:\whisper\whisper-playground>cd backend

(whisper) D:\whisper\whisper-playground\backend>python server.py
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
======== Running on http://0.0.0.0:8000 ========
(Press CTRL+C to quit)
INFO:root:Client connected, initializing stream...
INFO:root:Stream configuration received: {'model': 'small', 'transcribeTimeout': '5', 'language': 'english', 'transcriptionMethod': 'real-time', 'beamSize': '1'}
Downloading (…)26910443/config.json: 100%|████████████████████████████████████████| 2.66k/2.66k [00:00<00:00, 1.54MB/s]
Downloading (…)10443/tokenizer.json: 100%|████████████████████████████████████████| 2.13M/2.13M [00:00<00:00, 2.16MB/s]
Downloading (…)10443/vocabulary.txt: 100%|███████████████████████████████████████████| 422k/422k [00:00<00:00, 698kB/s]
Downloading model.bin: 100%|████████████████████████████████████████████████████████| 484M/484M [00:13<00:00, 36.5MB/s]]
Exception in thread Thread-1:██████████████████████████████████████████████████████▊| 482M/484M [00:13<00:00, 21.4MB/s]]
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\whisper\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\anaconda3\envs\whisper\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\anaconda3\envs\whisper\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\ProgramData\anaconda3\envs\whisper\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\whisper\whisper-playground\backend\client_manager.py", line 15, in create_new_client
    new_client = initialize_client(sid, sio, config)
  File "D:\whisper\whisper-playground\backend\clients\utils.py", line 58, in initialize_client
    new_client = client_class(sid, socket, transcriber, transcription_timeout)
  File "D:\whisper\whisper-playground\backend\clients\RealTimeClient.py", line 19, in __init__
    self.diarization_pipeline = OnlineSpeakerDiarization(self.pipeline_config)
  File "C:\ProgramData\anaconda3\envs\whisper\lib\site-packages\diart\blocks\diarization.py", line 44, in __init__
    self.segmentation = SpeakerSegmentation(self._config.segmentation, self._config.device)
  File "C:\ProgramData\anaconda3\envs\whisper\lib\site-packages\diart\blocks\segmentation.py", line 17, in __init__
    self.model.to(self.device)
  File "C:\ProgramData\anaconda3\envs\whisper\lib\site-packages\diart\models.py", line 38, in to
    self.load()
  File "C:\ProgramData\anaconda3\envs\whisper\lib\site-packages\diart\models.py", line 35, in load
    self.model = self.get_model()
  File "C:\ProgramData\anaconda3\envs\whisper\lib\site-packages\diart\models.py", line 20, in __call__
    return pyannote_loader.get_model(self.model_info, self.hf_token)
  File "C:\ProgramData\anaconda3\envs\whisper\lib\site-packages\pyannote\audio\pipelines\utils\getter.py", line 75, in get_model
    model = Model.from_pretrained(
  File "C:\ProgramData\anaconda3\envs\whisper\lib\site-packages\pyannote\audio\core\model.py", line 786, in from_pretrained
    path_for_pl = hf_hub_download(
  File "C:\ProgramData\anaconda3\envs\whisper\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\whisper\lib\site-packages\huggingface_hub\file_download.py", line 1181, in hf_hub_download
    headers = build_hf_headers(
  File "C:\ProgramData\anaconda3\envs\whisper\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\whisper\lib\site-packages\huggingface_hub\utils\_headers.py", line 121, in build_hf_headers
    token_to_send = get_token_to_send(token)
  File "C:\ProgramData\anaconda3\envs\whisper\lib\site-packages\huggingface_hub\utils\_headers.py", line 153, in get_token_to_send
    raise LocalTokenNotFoundError(
huggingface_hub.utils._headers.LocalTokenNotFoundError: Token is required (`token=True`), but no token found. You need to provide a token or be logged in to Hugging Face with `huggingface-cli login` or `huggingface_hub.login`. See https://huggingface.co/settings/tokens.
```

I tried clearing the model files in the Hugging Face cache, and it redownloaded the model.
I compared the model.bin file in the cache with the model.bin file from the official website and found that their MD5 checksums are the same.
This time it displayed different error messages， Is it due to network issues on my end?

**Comment by ethanzrd** [comment]
I clearly forgot to include the important step of accepting the terms and conditions of these models, could you review the additional steps in the branch attached to this issue [fix/huggingface](https://github.com/saharmor/whisper-playground/tree/fix/huggingface) and let me know if the issue is resolved? The previous issue you had is indeed resolved.

**Comment by Epresin** [comment]
I created an account and agreed to the terms of three models. The original error has disappeared, but this time it's showing an SSL error here. I believe this is due to my network, as the Chinese government restricts citizens from connecting to overseas websites.

```
(whisper) D:\whisper\whisper-playground\backend>python server.py
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
======== Running on http://0.0.0.0:8000 ========
(Press CTRL+C to quit)
INFO:root:Client connected, initializing stream...
INFO:root:Stream configuration received: {'transcribeTimeout': '5', 'language': 'english', 'model': 'small', 'transcriptionMethod': 'real-time', 'beamSize': '1'}
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\whisper\lib\site-packages\urllib3\connectionpool.py", line 711, in urlopen
    self._prepare_proxy(conn)
  File "C:\ProgramData\anaconda3\envs\whisper\lib\site-packages\urllib3\connectionpool.py", line 1007, in _prepare_proxy    conn.connect()
  File "C:\ProgramData\anaconda3\envs\whisper\lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "C:\ProgramData\anaconda3\envs\whisper\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\ProgramData\anaconda3\envs\whisper\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\ProgramData\anaconda3\envs\whisper\lib\ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\ProgramData\anaconda3\envs\whisper\lib\ssl.py", line 1041, in _create
    self.do_handshake()
  File "C:\ProgramData\anaconda3\envs\whisper\lib\ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\whisper\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\ProgramData\anaconda3\envs\whisper\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "C:\ProgramData\anaconda3\envs\whisper\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Max retries exceeded with url: /pyannote/segmentation/0b5b3216d60a2d32fc086b47ea8c67589aaeb26b7e07fcbe620d6d0b83e209ea?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27pytorch_model.bin%3B+filename%3D%22pytorch_model.bin%22%3B&response-content-type=application%2Foctet-stream&Expires=1692112928&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5MjExMjkyOH19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9weWFubm90ZS9zZWdtZW50YXRpb24vMGI1YjMyMTZkNjBhMmQzMmZjMDg2YjQ3ZWE4YzY3NTg5YWFlYjI2YjdlMDdmY2JlNjIwZDZkMGI4M2UyMDllYT9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSomcmVzcG9uc2UtY29udGVudC10eXBlPSoifV19&Signature=ruPacju3GcydZd-iEp5vht4DgqGZ2ZK~W95VOeZEY9T2HsH3U4hcG~ziAHoPM1dXvJOduSc8fJv7FUAVpVAbB~3vMNHgHuMSl-pGNojR8ZlHm3iEnO3LIAjC441zh~Zol7Gv9wE~9FsUxm7zal1X3QWHN5W8MOue9AwwcLhFg9gf876J75vGx9QWxjS4-1fo90cvkxjSpwA1TgwwTgBFdTe9N6AGrqzKo0DaTqQyNx~cFJP7O-kugGOF3Xul8jESrWTQMDmYg1i0XnL0E9WwtZ1n7ytBLHKR1kikcuUkPKjLhuEZrnHZBim-IR-8dRDBbZMFMMIus0OvaCIJSVViaA__&Key-Pair-Id=KVTP0A1DKRTAX (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))
```
I will try using a proxy to connect to Hugging Face. Additionally, I'd like to ask if there is a manual method for downloading models?

**Comment by ethanzrd** [comment]
I recommend you review this issue: [Error code 126 - faster-whisper](https://github.com/guillaumekln/faster-whisper/issues/85), it includes some fixes!
